### ISSUE TITLE
Not able to create lab reports and medical reports

### ISSUE THREAD

**Issue by ugintl** [MartMbithi/HMIS#1]
When I click on "Create New" Laboratory report and Medical report. See screenshots below.

Create New Laboratory Report

![lab](https://user-images.githubusercontent.com/12570802/130988808-536dbd04-7b7a-46a7-b397-93c42692e681.png)

Create New Medical Report

![medical1](https://user-images.githubusercontent.com/12570802/130988877-bb9ebac1-5b98-4a1f-aacc-d4f88112becf.png)

**Comment by MartMbithi** [comment]
Hello @ugintl , there was a bug in database design, and its fixed just re clone the repo and re import the database again.

**Comment by ugintl** [comment]
@MartMbithi Thanks. I will try it. There is another repo I would recommend you to test. I am sure you will like it. There seems to be similar problem with the lab reports section. I have created a issue as well. Can you give it a quick professional eye? https://github.com/bibekadh/Smart-Clinic-and-Lab-Systems

Here is the issue I created https://github.com/bibekadh/Smart-Clinic-and-Lab-Systems/issues/1

**Comment by ugintl** [comment]
@MartMbithi It worked thanks.
