### ISSUE TITLE
Steps to reproduce

### ISSUE THREAD

**Issue by akebu6** [MartMbithi/HMIS#4]
Hey, could you add details of how others can be able to run your project on their machines. It would be helpful to know if the project uses CodeIgniter, Laravel or just pure PHP and how to run it

**Comment by MartMbithi** [comment]
Hello @akebu6 , This project is done using pure PHP. 
To run it, kindly follow the following steps
1. Install XAMPP, WAMPP or LAMPP stack
2. Clone this repo under htdocs of your XAMPP, WAMPP or LAMPP directory
3. Create a database called martdevelopers_his.
4. Import the attached martdevelopers_his.sql file under database directory
5. On your browser, access it via this url - http://127.0.0.1/HMIS
6. For login credentials, check the attached readme file.

**Comment by akebu6** [comment]
Thank you so much 🙏

**Comment by akebu6** [comment]
@MartMbithi I was wondering if I could use some of your modules in my project? I won't use them in there current state but will modify them to meet my project's requirements. Is that okay?

**Comment by MartMbithi** [comment]
Yeah, its okay to use them. Also its an open source project you are working on, you can tag me along too. I would not mind.

**Comment by akebu6** [comment]
Awesome, thank you 😁
